name = "CookieCraft"
author = "ArkhamCookie"
version = "0.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fdd2e3bcabb52a10aa2449724d5b9d7b27755a1e04ca166db558358e5dcb9150"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
