name = "CookieCraft"
author = "ArkhamCookie"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d38225b9e03bd099bdd6cdf66602cb436114f38c376fe390a18280bbf6111a4"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21"]
