name = "CookieCraft"
author = "ArkhamCookie"
version = "0.15.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3c4bd0793c88acc867202b318b69c8d99dbf93e6c97c8e6d7973f1969d7ab09"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
