name = "CookieCraft"
author = "ArkhamCookie"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09b6d3c886f552d6c378f6b7651ee1d52820253e6c36eba485b3dfa6081a865a"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21"]
