name = "CookieCraft"
author = "ArkhamCookie"
version = "0.4.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a341bdedce3fc49857eab61f531264e7cfdc734f0148072d4cdc07484cbd540c"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
