name = "CookieCraft"
author = "ArkhamCookie"
version = "0.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49740e6d7d4a9ec297beac969a6e4119f29b409d470cbb0bb136a04fafaadb38"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
