name = "CookieCraft"
author = "ArkhamCookie"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae8d6b41694a984f904cb3cc0c656a22a1a03db7c74397044d1d16770e2cbcef"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
