name = "CookieCraft"
author = "ArkhamCookie"
version = "0.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "999dd6cef076d507ecf561da0c741f319853acc6743be091afc98e34eaf27692"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
