name = "CookieCraft"
author = "ArkhamCookie"
version = "0.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3d7b9a802876ba4b0799471de0e64d86f256b23b55ac125e7a460b75febae46"

[versions]
fabric = "0.16.2"
minecraft = "1.21"
