name = "CookieCraft"
author = "ArkhamCookie"
version = "0.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6ba0b828963e5485b963f6a19ad2057de470df9a3ab5aba33f0a93f4950ad12"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
